language: ruby
rvm: 
- 2.0.0
- 2.1.5
install: bundle install
notifications:
  email:
    recipients:
      - 8185408099@vtext.com
      - zenitram.oiram@gmail.com
    on_success: change
    on_failure: change
script: 
- bundle exec rspec
deploy:
  provider: rubygems
  api_key: 8116113f807f1b5e7b855f87c870cdd88045b1e9
  on:
    tags: true
    all_branches: true
    
